{{- include "common-lib.externalsecret" (list $ . "example-service" ) -}}
{{/*
Default configuration
*/}}
{{- define "secret.mydata.example-service" -}}
data:
  - secretKey: POSTGRES_HOST # pragma: allowlist-secret not actually a secret
    remoteRef:
      key: /tf/tikal_rnd/rds/tf-{{ .Values.shortEnv }}-{{ .Values.env }}-example-service-pgsql/address
{{- end }}
